#release configuration
#Fri Nov 14 14:11:21 EST 2025
projectVersionPolicyId=OddEvenVersionPolicy
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
project.rel.com.adobe.acs\:acs-aem-commons-ui.content=6.15.2
project.dev.com.adobe.acs\:acs-aem-commons-ui.apps=6.15.3-SNAPSHOT
project.scm.com.adobe.acs\:acs-aem-commons-ui.config.empty=true
project.dev.com.adobe.acs\:acs-aem-commons-bundle=6.15.3-SNAPSHOT
pinExternals=false
project.rel.com.adobe.acs\:acs-aem-commons-ui.config=6.15.2
project.rel.com.adobe.acs\:acs-aem-commons-ui.apps=6.15.2
project.scm.com.adobe.acs\:acs-aem-commons.tag=acs-aem-commons-6.15.2
project.rel.com.adobe.acs\:acs-aem-commons-bundle-onprem=6.15.2
project.dev.com.adobe.acs\:acs-aem-commons-ui.content=6.15.3-SNAPSHOT
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.rel.com.adobe.acs\:acs-aem-commons=6.15.2
project.scm.com.adobe.acs\:acs-aem-commons-bundle.empty=true
project.scm.com.adobe.acs\:acs-aem-commons-bundle-cloud.empty=true
project.scm.com.adobe.acs\:acs-aem-commons.developerConnection=scm\:git\:https\://github.com/Adobe-Consulting-Services/acs-aem-commons.git
exec.activateProfiles=cloud
pushChanges=true
project.scm.com.adobe.acs\:acs-aem-commons.connection=scm\:git\:git@github.com\:Adobe-Consulting-Services/acs-aem-commons.git
project.dev.com.adobe.acs\:acs-aem-commons-ui.config=6.15.3-SNAPSHOT
project.rel.com.adobe.acs\:acs-aem-commons-bundle-cloud=6.15.2
project.dev.com.adobe.acs\:acs-aem-commons=6.15.3-SNAPSHOT
project.scm.com.adobe.acs\:acs-aem-commons-bundle-onprem.empty=true
project.dev.com.adobe.acs\:acs-aem-commons-bundle-cloud=6.15.3-SNAPSHOT
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.dev.com.adobe.acs\:acs-aem-commons-all=6.15.3-SNAPSHOT
project.scm.com.adobe.acs\:acs-aem-commons-ui.apps.empty=true
project.rel.com.adobe.acs\:acs-aem-commons-bundle=6.15.2
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/Adobe-Consulting-Services/acs-aem-commons.git
scm.developmentCommitComment=@{prefix} prepare for next development iteration
project.rel.com.adobe.acs\:acs-aem-commons-all=6.15.2
exec.additionalArguments=-Dvault.skipValidation\=true
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.scm.com.adobe.acs\:acs-aem-commons-ui.content.empty=true
project.scm.com.adobe.acs\:acs-aem-commons-all.empty=true
scm.tag=acs-aem-commons-6.15.2
project.dev.com.adobe.acs\:acs-aem-commons-bundle-onprem=6.15.3-SNAPSHOT
project.scm.com.adobe.acs\:acs-aem-commons.url=https\://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/${project.scm.tag}
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
