name: Designite Workflow

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn clean install
      - name: Download DesigniteJava
        run: wget "https://www.designite-tools.com/static/download/DJE/DesigniteJava.jar"
      - name: Analyze project with DesigniteJava
        run: |
          java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat ${{ secrets.PAT }}
          ls
      - name: Upload Designite results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: DesigniteAnalysis
          path: Designite_output/DesigniteAnalysis.xml
      - name: Download DesigniteAnalysis artifact
        uses: actions/download-artifact@v2
        with:
          name: DesigniteAnalysis
          path: Designite_output
      - name: Send DesigniteAnalysis.xml to Analysis controller
        run: |
          curl -X POST -F 'file=@Designite_output/DesigniteAnalysis.xml' https://0931-156-34-1-52.ngrok.io/analysis/${{github.repository_id}}/${{github.ref_name}}